import { Component, OnDestroy, OnInit } from '@angular/core';
import {Base64} from 'js-base64/base64'
import { get } from 'scriptjs';
import { FileApiPath } from 'src/app/api_path/system/FileApiPath';
import { TaskService } from 'src/app/service/task/task.service';
import { ObjectUtils } from 'src/app/util/ObjectUtils';
import { RequestUtil } from 'src/app/util/RequestUtil';
import { RouteUtils } from 'src/app/util/RouteUtils';
/**
 * 声明JS中的对象，避免编译不通过
 */
declare var DocsAPI:any;

@Component({
  selector: 'app-preview',
  templateUrl: './preview.component.html',
  styleUrls: ['./preview.component.css']
})
export class PreviewComponent implements OnInit ,OnDestroy{

  constructor(private router:RouteUtils,private taskService:TaskService) { }
  isOkLoading = false
  isVisible=false
  api = null;

  handleOk(){
    if(this.api!=null&&this.saveurl!=null){
      this.isOkLoading = true;
      this.api.downloadAs()
    }
  }
  ngOnDestroy(): void {

    this.isVisible =  true;
    
    this.taskService.addTask(false,'showSub')
  }
  //保存的回调地址
  saveurl 
  // host = "192.168.3.53"
//  host="10.10.10.63"
  // host="10.10.10.63"
  // host = "127.0.0.1:8888"
  host = "127.0.0.1:8001"
  backhost = "192.168.30.11"
  data = [
    {
    "id":null,
    "node":"制定类条款",
    "subList":[
    {
    "id":12862,
    "labelType":"row",
    "name":"协议期限约定",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"协议期限奯合作期限奯本协议的合作期限自本协议签署之日起至2021年10月01日止。期限届满前30日若双方均未书面提出异议，本协议自动以同等条件自动延续一年。",
    "content":"协议期限奯合作期限奯本协议的合作期限自本协议签署之日起至2021年10月01日止。期限届满前30日若双方均未书面提出异议，本协议自动以同等条件自动延续一年。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"本条款约定：协议的起始日期、终止日期、续约等约定，涉及到协议效力，须谨慎修改；",
    "ruleSuggestion":"期限应当根据服务实际情况修改；",
    "ruleWarn":"协议期限约定有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"协议期限合作期限本协议的合作期限自本协议签署之日起至年月日止。期限届满前30日若双方均未书面提出异议，本协议自动以同等条件自动延续一年。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"81,82,83"
    },
    {
    "id":12864,
    "labelType":"row",
    "name":"协议终止情形",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"本协议于下列情形之一出现时即终止奯合作期限届满前390日双方任意一方以书面形式通知对方不再续约。奯出现本协议违约条款中的情形，守约方有权提前终止本协议。奯如果一方资不抵债，或被进行清算，或终止经营，或提出破产申请/被提出破产申请，或被宣告破产，或为债权人利益进行转让，或者其他协议方有理由相信或有证据表明其付款能力会受到影响，另一方有权通过书面通知立即终止服务而不需承担任何额外责任。奯双方均书面同意解除协议。",
    "content":"本协议于下列情形之一出现时即终止奯合作期限届满前90日双方任意一方以书面形式通知对方不再续约。奯出现本协议违约条款中的情形，守约方有权提前终止本协议。奯如果一方资不抵债，或被进行清算，或终止经营，或提出破产申请/被提出破产申请，或被宣告破产或者其他协议方有理由相信或有证据表明其付款能力会受到影响，另一方有权通过书面通知立即终止服务而不需承担任何额外责任。奯双方均书面同意解除协议。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"本条款约定协议终止的适用情形，不得随意修改；",
    "ruleSuggestion":"协议不能随意终止；",
    "ruleWarn":"协议终止情形被更改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":"本协议于下列情形之一出现时即终止奯合作期限届满前90日双方任意一方以书面形式通知对方不再续约。奯出现本协议违约条款中的情形，守约方有权提前终止本协议。奯如果一方资不抵债，或被进行清算，或终止经营，或提出破产申请/被提出破产申请，或被宣告破产或者其他协议方有理由相信或有证据表明其付款能力会受到影响，另一方有权通过书面通知立即终止服务而不需承担任何额外责任。奯双方均书面同意解除协议。",
    "value":"本协议于下列情形之一出现时即终止合作期限届满前30日双方任意一方以书面形式通知对方不再续约。出现本协议违约条款中的情形，守约方有权提前终止本协议。如果一方资不抵债，或被进行清算，或终止经营，或提出破产申请/被提出破产申请，或被宣告破产，或为债权人利益进行转让，或者其他协议方有理由相信或有证据表明其付款能力会受到影响，另一方有权通过书面通知立即终止服务而不需承担任何额外责任。双方均书面同意解除协议。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"85,86,87,88,89"
    },
    {
    "id":12867,
    "labelType":"row",
    "name":"双方廉政承诺",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"廉政条款奯在合作过程中，为合规经营，各方严格遵守国家法律和廉政建设的规定与制度以及相关行业行风建设的纪律和规定。各方应对各自工作人员开展廉政教育，增强相关人员廉洁自律的意识，以维护各方共同利益，促进各方关系良好发展。奯（1）严格遵守党和国家有关法律法规的有关规定，严禁商业贿赂行为。奯（2）各方的业务活动坚持公开、公正、诚信、透明的原则(法律认定的商业秘密和合同文件另有规定除外)，不得损害国家和其他第三方的合法利益。奯（3）各方应当严格防范利益冲突，利益冲突包括但不限于：奯A.各方工作人员、工作人员的关系人不得索要或接受对方及其工作人员、工作人员的关系人提供的不正当利益。奯B.各方及其工作人员、工作人员的关系人应严格按本协议及法律法规办事，不得为谋取私利向对方或对方工作人员及其关系人行贿，私下串通，损害双方利益。奯C.各方对对方及其工作人员、工作人员的关系人提出的合同规定外的要求，有权予以拒绝。奯D.一方及该方工作人员及其关系人不得与对方及对方工作人员及其关系人有任何形式的借款或其他债务关系、除公司正常业务以外的合作关系；奯E.一方及其关联公司的股东、监事、经理、高级管理人员、合作项目负责人及项目成员系对方工作人员或其关系人的，应在与对方开展业务前以书面方式如实、全面告知对方。奯F.各方合作及开展业务过程中，一方不得允许对方工作人员及其关系人持有或由第三方代持有对方及其关联公司股权、债券，亦不得聘用对方工作人员（包括但不限于建立正式劳动关系、劳务派遣、外包服务、兼职、咨询顾问等其他形式）。一方及其关联公司如有聘用对方工作人员及其关系人任职于对方的，应在聘用之日起三日内以书面方式如实、全面告知对方。奯（4）发现对方在业务活动中有违反禁止商业贿赂的行为的，有及时提醒对方纠正的权利和义务。奯（5）发现对方严重违反本合同义务条款的行为，有权向有关机关检举、举报。奯（6）建立健全廉政制度，开展廉政告知教育活动，公布投诉举报电话。奯（7）各方应当建立健全账簿、凭证、财务核算制度。若守约方收到举报信息或通过其他方式发现另一方在业务活动中有违反廉政规定的行为，守约方有权向涉嫌违反的另一方了解合同履行情况、查看相关资料（包括但不限于财务报表等）等其他方式进行廉政监督，该方应当积极/无条件予以配合。奯（8）各方廉政部将会对对方所有信息提供者及所提供的全部资料严格保密，并对各方在对方中的正当利益予以保护。奯各方接受投诉举报的联络方式：奯举报邮箱举报电话甲方乙方",
    "content":"廉政条款奯在合作过程中，为合规经营，各方严格遵守国家法律和廉政建设的规定与制度以及相关行业行风建设的纪律和规定。各方应对各自工作人员开展廉政教育，增强相关人员廉洁自律的意识，以维护各方共同利益，促进各方关系良好发展。奯（1）严格遵守党和国家有关法律法规的有关规定，严禁商业贿赂行为。奯（2）各方的业务活动坚持公开、公正、诚信、透明的原则(法律认定的商业秘密和合同文件另有规定除外)，不得损害国家和其他第三方的合法利益。奯（3）各方应当严格防范利益冲突，利益冲突包括但不限于：奯A.各方工作人员、工作人员的关系人不得索要或接受对方及其工作人员、工作人员的关系人提供的不正当利益。奯B.各方及其工作人员、工作人员的关系人应严格按本协议及法律法规办事，不得为谋取私利向对方或对方工作人员及其关系人行贿，私下串通，损害双方利益。奯奯D.一方及该方工作人员及其关系人不得与对方及对方工作人员及其关系人有任何形式的借款或其他债务关系、除公司正常业务以外的合作关系；奯E.一方及其关联公司的股东、监事、经理、高级管理人员、合作项目负责人及项目成员系对方工作人员或其关系人的，应在与对方开展业务前以书面方式如实、全面告知对方。奯F.各方合作及开展业务过程中，一方不得允许对方工作人员及其关系人持有或由第三方代持有对方及其关联公司股权、债券，亦不得聘用对方工作人员（包括但不限于建立正式劳动关系、劳务派遣、外包服务、兼职、咨询顾问等其他形式）。一方及其关联公司如有聘用对方工作人员及其关系人任职于对方的，应在聘用之日起三日内以书面方式如实、全面告知对方。奯（4）发现对方在业务活动中有违反禁止商业贿赂的行为的，有及时提醒对方纠正的权利和义务。奯（5）发现对方严重违反本合同义务条款的行为，有权向有关机关检举、举报。奯（6）建立健全廉政制度，开展廉政告知教育活动，公布投诉举报电话。奯（7）各方应当建立健全账簿、凭证、财务核算制度。若守约方收到举报信息或通过其他方式发现另一方在业务活动中有违反廉政规定的行为，守约方有权向涉嫌违反的另一方了解合同履行情况、查看相关资料（包括但不限于财务报表等）等其他方式进行廉政监督，该方应当积极/无条件予以配合。奯（8）各方廉政部将会对对方所有信息提供者及所提供的全部资料严格保密，并对各方在对方中的正当利益予以保护。奯各方接受投诉举报的联络方式：奯举报邮箱举报电话甲方乙方",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"本条款约定合同当事方的廉政廉洁保证与承诺，是双方遵守维护法律法规、市场交易秩序、职业道德操守的保障；",
    "ruleSuggestion":"恢复原模板标准条款或在不违反法律法规的情形下增加相关约定条款；",
    "ruleWarn":"双方廉政承诺条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"廉政条款在合作过程中，为合规经营，各方严格遵守国家法律和廉政建设的规定与制度以及相关行业行风建设的纪律和规定。各方应对各自工作人员开展廉政教育，增强相关人员廉洁自律的意识，以维护各方共同利益，促进各方关系良好发展。（1）严格遵守党和国家有关法律法规的有关规定，严禁商业贿赂行为。（2）各方的业务活动坚持公开、公正、诚信、透明的原则(法律认定的商业秘密和合同文件另有规定除外)，不得损害国家和其他第三方的合法利益。（3）各方应当严格防范利益冲突，利益冲突包括但不限于：A.各方工作人员、工作人员的关系人不得索要或接受对方及其工作人员、工作人员的关系人提供的不正当利益。B.各方及其工作人员、工作人员的关系人应严格按本协议及法律法规办事，不得为谋取私利向对方或对方工作人员及其关系人行贿，私下串通，损害双方利益。C.各方对对方及其工作人员、工作人员的关系人提出的合同规定外的要求，有权予以拒绝。D.一方及该方工作人员及其关系人不得与对方及对方工作人员及其关系人有任何形式的借款或其他债务关系、除公司正常业务以外的合作关系；E.一方及其关联公司的股东、监事、经理、高级管理人员、合作项目负责人及项目成员系对方工作人员或其关系人的，应在与对方开展业务前以书面方式如实、全面告知对方。F.各方合作及开展业务过程中，一方不得允许对方工作人员及其关系人持有或由第三方代持有对方及其关联公司股权、债券，亦不得聘用对方工作人员（包括但不限于建立正式劳动关系、劳务派遣、外包服务、兼职、咨询顾问等其他形式）。一方及其关联公司如有聘用对方工作人员及其关系人任职于对方的，应在聘用之日起三日内以书面方式如实、全面告知对方。（4）发现对方在业务活动中有违反禁止商业贿赂的行为的，有及时提醒对方纠正的权利和义务。（5）发现对方严重违反本合同义务条款的行为，有权向有关机关检举、举报。（6）建立健全廉政制度，开展廉政告知教育活动，公布投诉举报电话。（7）各方应当建立健全账簿、凭证、财务核算制度。若守约方收到举报信息或通过其他方式发现另一方在业务活动中有违反廉政规定的行为，守约方有权向涉嫌违反的另一方了解合同履行情况、查看相关资料（包括但不限于财务报表等）等其他方式进行廉政监督，该方应当积极/无条件予以配合。（8）各方廉政部将会对对方所有信息提供者及所提供的全部资料严格保密，并对各方在对方中的正当利益予以保护。各方接受投诉举报的联络方式：举报邮箱举报电话甲方乙方"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113"
    },
    {
    "id":12866,
    "labelType":"row",
    "name":"争议解决",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"本协议适用《中华人民共和国合同法》等国家有关法律法规。对于因本协议的解释和执行而产生的争议，以及履行本协议过程中产生的分歧和纠纷，应首先由双方通过友好协商或经由中立的第三方来调解解决；如未能于前述方式在开始协商后30日内解决，则任何一方均有权将相关争议、分歧、纠纷提交原被告方所在地人民法院管辖。",
    "content":"本协议适用《中华人民共和国合同法》等国家有关法律法规。对于因本协议的解释和执行而产生的争议，以及履行本协议过程中产生的分歧和纠纷，应首先由双方通过友好协商或经由中立的第三方来调解解决；如未能于前述方式在开始协商后30日内解决，则任何一方均有权将相关争议、分歧、纠纷提交被告方所在地人民法院管辖。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"本条款约定合同争议解决方式，协商作为前置程序，协商不成时进行诉讼或仲裁方式；",
    "ruleSuggestion":"协商作为前置方式，协商不成时可诉讼或仲裁；",
    "ruleWarn":"争议解决条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"本协议适用《中华人民共和国合同法》等国家有关法律法规。对于因本协议的解释和执行而产生的争议，以及履行本协议过程中产生的分歧和纠纷，应首先由双方通过友好协商或经由中立的第三方来调解解决；如未能于前述方式在开始协商后30日内解决，则任何一方均有权将相关争议、分歧、纠纷提交原告方所在地人民法院管辖。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"95"
    },
    {
    "id":12868,
    "labelType":"row",
    "name":"通知与送达条款",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"通知与联系奯除协议另有约定外，各方因订立和履行本协议而相互发出的通知、文件、资料均为本协议的组成部分，与本协议具有同等法律效力，前述通知、文件、资料通过以下列传真、邮寄或电子邮件方式送达。各方需保存相关电子邮件以便查验。奯各方的指定联系方式如首页所示。一方联系方式发生变更的，应当在变更前57个工作日书面通知对方。奯通过传真方式的，发出传真时视为送达；以邮寄方式的，投送到邮寄地址视为送达；以电子邮件方式发送的，自发出时起24小时视为送达。奯任何一方向对方发出通知，以多种方式通知的，以对方最早接收到通知的日期为通知送达日期。 ",
    "content":"通知与联系奯除协议另有约定外，各方因订立和履行本协议而相互发出的通知、文件、资料均为本协议的组成部分，与本协议具有同等法律效力，前述通知、文件、资料通过以下列传真、邮寄或电子邮件方式送达。各方需保存相关电子邮件以便查验。奯各方的指定联系方式如首页所示。一方联系方式发生变更的，应当在变更前7个工作日书面通知对方。奯通过传真方式的，发出传真时视为送达；以邮寄方式的，投送到邮寄地址视为送达；以电子邮件方式发送的，自发出时起24小时视为送达。奯任何一方向对方发出通知，以多种方式通知的，以对方最早接收到通知的日期为通知送达日期。 ",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":"通知与联系\n(1) 除协议另有约定外，各方因订立和履行本协议而相互发出的通知、文件、资料均为本协议的组成部分，与本协议具有同等法律效力，前述通知、文件、资料通过以下列传真、邮寄或电子邮件方式送达。各方需保存相关电子邮件以便查验。\n(2) 各方的指定联系方式如首页所示。一方联系方式发生变更的，应当在变更前5个工作日书面通知对方。\n(3) 通过传真方式的，发出传真时视为送达；以邮寄方式的，投送到邮寄地址视为送达；以电子邮件方式发送的，自发出时起24小时视为送达。\n(4) 任何一方向对方发出通知，以多种方式通知的，以对方最早接收到通知的日期为通知送达日期。",
    "ruleRisk":"通知与送达条款约定合同中通知送达的形式、变更联系方式等事项，被修改可能会影响通知义务的履行、通知的有效送达，需谨慎修改；",
    "ruleSuggestion":"不建议使用口头通知方式；",
    "ruleWarn":"通知与送达条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"通知与联系除协议另有约定外，各方因订立和履行本协议而相互发出的通知、文件、资料均为本协议的组成部分，与本协议具有同等法律效力，前述通知、文件、资料通过以下列传真、邮寄或电子邮件方式送达。各方需保存相关电子邮件以便查验。各方的指定联系方式如首页所示。一方联系方式发生变更的，应当在变更前5个工作日书面通知对方。通过传真方式的，发出传真时视为送达；以邮寄方式的，投送到邮寄地址视为送达；以电子邮件方式发送的，自发出时起24小时视为送达。任何一方向对方发出通知，以多种方式通知的，以对方最早接收到通知的日期为通知送达日期。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"114,115,116,117,118"
    },
    {
    "id":12863,
    "labelType":"row",
    "name":"协议终止约定",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"协议期间，一方欲变更或终止协议，需提前30日以书面方式提出，经双方协商一致可书面变更或终止协议。若一方未经对方同意，擅自变更或终止本协议，则需赔偿另一方因此而遭受的直接经济损失。奯双方对未支付金额无异议情况下，甲方应在本协议终止日后三七天内向乙方支付全部未支付金额。",
    "content":"协议期间，一方欲变更或终止协议，需提前30日以书面方式提出，经双方协商一致可书面变更或终止协议。若一方未经对方同意，擅自变更或终止本协议，则需赔偿另一方因此而遭受的直接经济损失。奯双方对未支付金额无异议情况下，甲方应在本协议终止日后七天内向乙方支付全部未支付金额。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"本条款约定协议终止的程序和条件；",
    "ruleSuggestion":"不建议修改，协议终止的条件和程序应当由双方确认，并在最小程度减少对双方的不利影响；；",
    "ruleWarn":"协议终止约定有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":"协议期间，一方欲变更或终止协议，需提前30日以书面方式提出，经双方协商一致可书面变更或终止协议。若一方未经对方同意，擅自变更或终止本协议，则需赔偿另一方因此而遭受的直接经济损失。奯双方对未支付金额无异议情况下，甲方应在本协议终止日后七天内向乙方支付全部未支付金额。",
    "value":"协议期间，一方欲变更或终止协议，需提前30日以书面方式提出，经双方协商一致可书面变更或终止协议。若一方未经对方同意，擅自变更或终止本协议，则需赔偿另一方因此而遭受的直接经济损失。双方对未支付金额无异议情况下，甲方应在本协议终止日后三天内向乙方支付全部未支付金额。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"84,90"
    },
    {
    "id":12861,
    "labelType":"row",
    "name":"知识产权条款",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"知识产权奯在履行本协议期间，甲乙双方在使用其他协议签署方的企业名称、商标、商号、品牌、域名和网站时，应当完全单独为甲乙双方在本协议中约定的内容服务，不得夹带其他业务内容或经营目的；甲乙双方在其自身宣传材料、名片、市场宣传、网站建设以及其他任何方面使用其他协议签署方拥有的名称、域名和网站，都必须事先书面通知对方，并获得对方的书面许可后方可进行；否则一方有权随时以书面形式通知其他协议签署方终止协议，由侵权行为方承担由此而产生的一切法律责任，并赔偿因此造成的一切损失。奯甲乙双方及其职员承诺在履行本协议期间及在本协议期满后不对对方所拥有的商标、企业名称、域名等进行贬低或者其它任何损害，也不对对方互联网网页或者网站进行任何贬低、抄袭、歪曲、破坏或其它损害。奯本协议有效期内及本协议终止或者解除后，甲乙双方承诺不向任何非本协议签署方（包括但不限于与对方构成商业竞争关系的企业、商业机构或者组织）提供有关双方业务、技术等一切相关信息或者资料，否则由一方承担相应的责任，并赔偿另一方因此造成的一切损失。",
    "content":"知识产权奯在履行本协议期间，甲乙双方在使用其他协议签署方的企业名称、商标、商号、品牌、域名和网站时，应当完全单独为甲乙双方在本协议中约定的内容服务，不得夹带其他业务内容或经营目的；甲乙双方在其自身宣传材料、名片、市场宣传、网站建设以及其他任何方面使用其他协议签署方拥有的名称、域名和网站，都必须事先书面通知对方，并获得对方的书面许可后方可进行；否则一方有权随时以书面形式通知其他协议签署方终止协议，由侵权行为方承担由此而产生的一切法律责任，并赔偿因此造成的一切损失。奯甲乙双方及其职员承诺在履行本协议期间及在本协议期满后不对对方所拥有的商标、企业名称、域名等进行贬低或者其它任何损害，也不对对方互联网网页或者网站进行任何贬低、抄袭、歪曲、破坏或其它损害。奯本协议有效期内及本协议终止或者解除后，甲乙双方承诺不向任何非本协议签署方（包括但不限于与对方构成商业竞争关系的企业、商业机构或者组织）提供有关双方业务、技术等一切相关信息或者资料，否则由一方承担相应的责任，并赔偿另一方因此造成的一切损失。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":"1、 在履行本协议期间，甲乙双方在使用其他协议签署方的企业名称、商标、商号、品牌、域名和网站时，应当完全单独为甲乙双方在本协议中约定的内容服务，不得夹带其他业务内容或经营目的；甲乙双方在其自身宣传材料、名片、市场宣传、网站建设以及其他任何方面使用其他协议签署方拥有的名称、域名和网站，都必须事先书面通知对方，并获得对方的书面许可后方可进行；否则一方有权随时以书面形式通知其他协议签署方终止协议，由侵权行为方承担由此而产生的一切法律责任，并赔偿因此造成的一切损失。\n2、 甲乙双方及其职员承诺在履行本协议期间及在本协议期满后不对对方所拥有的商标、企业名称、域名等进行贬低或者其它任何损害，也不对对方互联网网页或者网站进行任何贬低、抄袭、歪曲、破坏或其它损害。\n3、 本协议有效期内及本协议终止或者解除后，甲乙双方承诺不向任何非本协议签署方（包括但不限于与对方构成商业竞争关系的企业、商业机构或者组织）提供有关双方业务、技术等一切相关信息或者资料，否则由一方承担相应的责任，并赔偿另一方因此造成的一切损失。",
    "ruleRisk":"本条款约定，在合同履行过程中双方知识产权适用权限、限制、相关责任的承担，是知识产权权益的保障；",
    "ruleSuggestion":"建议恢复原模板标准条款；",
    "ruleWarn":"知识产权条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"知识产权在履行本协议期间，甲乙双方在使用其他协议签署方的企业名称、商标、商号、品牌、域名和网站时，应当完全单独为甲乙双方在本协议中约定的内容服务，不得夹带其他业务内容或经营目的；甲乙双方在其自身宣传材料、名片、市场宣传、网站建设以及其他任何方面使用其他协议签署方拥有的名称、域名和网站，都必须事先书面通知对方，并获得对方的书面许可后方可进行；否则一方有权随时以书面形式通知其他协议签署方终止协议，由侵权行为方承担由此而产生的一切法律责任，并赔偿因此造成的一切损失。甲乙双方及其职员承诺在履行本协议期间及在本协议期满后不对对方所拥有的商标、企业名称、域名等进行贬低或者其它任何损害，也不对对方互联网网页或者网站进行任何贬低、抄袭、歪曲、破坏或其它损害。本协议有效期内及本协议终止或者解除后，甲乙双方承诺不向任何非本协议签署方（包括但不限于与对方构成商业竞争关系的企业、商业机构或者组织）提供有关双方业务、技术等一切相关信息或者资料，否则由一方承担相应的责任，并赔偿另一方因此造成的一切损失。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"77,78,79,80"
    }
    ]
    },
    {
    "id":null,
    "node":"违约责任",
    "subList":[
    {
    "id":12853,
    "labelType":"row",
    "name":"合同变更违约责任",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"甲、乙双方任何一方如遇搬迁或企业地址变更、联系人变更或授权代表人变更，应及时书面通知对方，否则因此所产生的直接经济损失由未履行通知义务的一方负责承担。",
    "content":"甲、乙双方任何一方如遇搬迁或企业地址变更、联系人变更或授权代表人变更，应及时书面通知对方，否则因此所产生的直接经济损失由未履行通知义务的一方负责承担。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":"甲、乙双方任何一方如遇搬迁或企业地址变更、联系人变更或授权代表人变更，应及时书面通知对方，否则因此所产生的直接经济损失由未履行通知义务的一方负责承担。",
    "ruleRisk":"本条款约定双方任何一方工商信息、联系方式、授权人等信息变更，应及时书面通知对方，否则因此所产生的直接经济损失由未履行通知义务的一方负责承担；有利于合同双方信息同步，能避免双方沟通交流受阻、合同履行产生矛盾争议；",
    "ruleSuggestion":"建议恢复原模板标准条款；",
    "ruleWarn":"合同变更违约责任条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"甲、乙双方任何一方如遇搬迁或企业地址变更、联系人变更或授权代表人变更，应及时书面通知对方，否则因此所产生的直接经济损失由未履行通知义务的一方负责承担。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"65"
    }
    ]
    },
    {
    "id":null,
    "node":"协议起始/终止时间",
    "subList":[
    {
    "id":12789,
    "labelType":"content",
    "name":"签署年份",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"2018",
    "content":"2018",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"结合实际情况，本年度为公元2020年，合同签署日期不可能在2020年之前，否则合同签署日期、生效日期不符合合同效力逻辑；合同审核与签署必然具有前置性，不可倒签合同；",
    "ruleSuggestion":"请重新核对签署年份信息；",
    "ruleWarn":"签署年份有误",
    "rules":[
    {
    "compareType":null,
    "key":null,
    "oper":"",
    "source":null,
    "value":"${181-协议起始/终止时间-签署年份}>=2020"
    }
    ],
    "type":"calculate"
    }
    }
    ],
    "rowNums":""
    }
    ]
    },
    {
    "id":null,
    "node":"保密与不可抗力条款",
    "subList":[
    {
    "id":12857,
    "labelType":"row",
    "name":"保密违约责任",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"对于以下信息，双方均免除保密责任：由公众通过合法途径获知的信息；从非本协议签署方获知的，并未违反任何保密责任的信息；为法律或有管辖权的政府部门根据法令所要求透露的信息，或者根据法律程序而要求透露的信息。奯未经相对方事先书面同意，任何一方不得将对方的公司商业秘密信息、自然人身份信息泄露给任何其他第三方，该商业秘密等其他信息包括但不限于任何一方可能接触到的对方公司信息、组织架构、专人组的联系方式等信息。若任何一方违反上述保密义务，应当赔偿对方因此遭受到的所有损失。",
    "content":"对于以下信息，双方均免除保密责任：由公众通过合法途径获知的信息；从非本协议签署方获知的，并未违反任何保密责任的信息；为法律或有管辖权的政府部门根据法令所要求透露的信息，或者根据法律程序而要求透露的信息。奯未经相对方事先书面同意，任何一方不得将对方的公司商业秘密信息、自然人身份信息泄露给任何其他第三方，该商业秘密等其他信息包括但不限于任何一方可能接触到的对方公司信息、组织架构、专人组的联系方式等信息。若任何一方违反上述保密义务，应当赔偿对方因此遭受到的所有损失。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"本条款约定保密责任的免除和承担，涉及到信息安全与权益保障，需谨慎修改；",
    "ruleSuggestion":"建议恢复原模板标准条款；",
    "ruleWarn":"保密约定有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"对于以下信息，双方均免除保密责任：由公众通过合法途径获知的信息；从非本协议签署方获知的，并未违反任何保密责任的信息；为法律或有管辖权的政府部门根据法令所要求透露的信息，或者根据法律程序而要求透露的信息。未经相对方事先书面同意，任何一方不得将对方的公司商业秘密信息、自然人身份信息泄露给任何其他第三方，该商业秘密等其他信息包括但不限于任何一方可能接触到的对方公司信息、组织架构、专人组的联系方式等信息。若任何一方违反上述保密义务，应当赔偿对方因此遭受到的所有损失。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"72,73"
    },
    {
    "id":12856,
    "labelType":"row",
    "name":"保密义务",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"对于本协议中描述的保密信息，双方应当奯以不低于保护自己保密信息的程度（至少以合理程度）予以保密；奯要求获知保密信息的人员对保密信息予以保密；奯在必要情况下，根据双方书面商定的方式使用保密信息。",
    "content":"对于本协议中描述的保密信息，双方应当奯以不低于保护自己保密信息的程度（至少以合理程度）予以保密；奯要求获知保密信息的人员对保密信息予以保密；奯在必要情况下，根据双方书面商定的方式使用保密信息。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"本条款约定保密义务履行的形式，影响到保密方式是否有效起到保密信息的作用，需谨慎修改；",
    "ruleSuggestion":"禁止行为、保密义务、保密形式不建议修改；",
    "ruleWarn":"保密义务条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"对于本协议中描述的保密信息，双方应当以不低于保护自己保密信息的程度（至少以合理程度）予以保密；要求获知保密信息的人员对保密信息予以保密；在必要情况下，根据双方书面商定的方式使用保密信息。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"68,69,70,71"
    },
    {
    "id":12859,
    "labelType":"row",
    "name":"不可抗力约定",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"不可抗力奯由于战争、地震、雷击、水灾、火灾、政府行为、黑客攻击、电信部门技术管制等不可抗力原因致使双方不能按约定履行协议，则本协议的履行时间应予以延期，双方均不对因不可抗力造成的损失承担责任。若不可抗力事件致使协议履行延期超过一个月的，本协议任何一方有权书面通知其他协议签署方立即终止本协议而无需承担违约责任。受影响的一方应在不可抗力发生后尽快以传真或电子邮件通知对方，并在有关机关出具证明书后三天内以最快方式向对方提供一切相关材料。",
    "content":"不可抗力奯由于战争、地震、雷击、水灾、火灾、政府行为、黑客攻击等不可抗力原因致使双方不能按约定履行协议，则本协议的履行时间应予以延期，双方均不对因不可抗力造成的损失承担责任。若不可抗力事件致使协议履行延期超过一个月的，本协议任何一方有权书面通知其他协议签署方立即终止本协议而无需承担违约责任。受影响的一方应在不可抗力发生后尽快以传真或电子邮件通知对方，并在有关机关出具证明书后三天内以最快方式向对方提供一切相关材料。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"本条款约定不可抗力的定义、范围、免责条件相关事项，涉及到合同的履行与免责终止，需谨慎修改；",
    "ruleSuggestion":"不可抗力的定义与范围应当明确具体，不可抗力应当不可预知、不可避免、不可抗拒；具有客观上的偶然性和不可避免性、主观上的不可预见性和社会危害性；",
    "ruleWarn":"不可抗力条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"不可抗力由于战争、地震、雷击、水灾、火灾、政府行为、黑客攻击、电信部门技术管制等不可抗力原因致使双方不能按约定履行协议，则本协议的履行时间应予以延期，双方均不对因不可抗力造成的损失承担责任。若不可抗力事件致使协议履行延期超过一个月的，本协议任何一方有权书面通知其他协议签署方立即终止本协议而无需承担违约责任。受影响的一方应在不可抗力发生后尽快以传真或电子邮件通知对方，并在有关机关出具证明书后三天内以最快方式向对方提供一切相关材料。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"75,76"
    },
    {
    "id":12858,
    "labelType":"row",
    "name":"保密期限",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"本保密条款不因本协议终止而失效。",
    "content":"本保密条款不因本协议终止而失效。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":"本保密条款不因本协议终止而失效。",
    "ruleRisk":"本标准模板约定保密条款持续有效；",
    "ruleSuggestion":"为保障双方信息保密，建议恢复原模板标准条款；",
    "ruleWarn":"保密期限有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"本保密条款不因本协议终止而失效。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"74"
    },
    {
    "id":12855,
    "labelType":"row",
    "name":"保密信息范围",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"保密条款奯兹就双方之间的合作，双方均承诺并保证其有义务不向非本协议签署方透露保密信息，该保密信息指由签署本协议的一方向其他本协议签署方透露的，与双方合作有关的任何口头或书面形式或其他形式的不公开信息，包括但不限于商业计划、客户名单、技术数据、产品构思、开发计划、职员名单及人员相关信息、企业商旅账号和密码、操作手册、财务情况和其他递交时约定为保密信息的资料（以下通称“保密信息”）。",
    "content":"保密条款奯兹就双方之间的合作，双方均承诺并保证其有义务不向非本协议签署方透露保密信息，该保密信息指由签署本协议的一方向其他本协议签署方透露的，与双方合作有关的任何口头或书面形式或其他形式的不公开信息，包括但不限于商业计划、客户名单、技术数据、产品构思、开发计划、职员名单及人员相关信息、企业商旅账号和密码、操作手册、财务情况和其他递交时约定为保密信息的资料（以下通称“保密信息”）。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":"兹就双方之间的合作，双方均承诺并保证其有义务不向非本协议签署方透露保密信息，该保密信息指由签署本协议的一方向其他本协议签署方透露的，与双方合作有关的任何口头或书面形式或其他形式的不公开信息，包括但不限于商业计划、客户名单、技术数据、产品构思、开发计划、职员名单及人员相关信息、企业商旅账号和密码、操作手册、财务情况和其他递交时约定为保密信息的资料（以下通称“保密信息”）。",
    "ruleRisk":"此处约定保密信息的定义与范围，涉及到信息安全，有效约束双方遵守保密义务，需谨慎修改；",
    "ruleSuggestion":"增加保密信息范围可以同意；",
    "ruleWarn":"保密信息范围有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"保密条款兹就双方之间的合作，双方均承诺并保证其有义务不向非本协议签署方透露保密信息，该保密信息指由签署本协议的一方向其他本协议签署方透露的，与双方合作有关的任何口头或书面形式或其他形式的不公开信息，包括但不限于商业计划、客户名单、技术数据、产品构思、开发计划、职员名单及人员相关信息、企业商旅账号和密码、操作手册、财务情况和其他递交时约定为保密信息的资料（以下通称“保密信息”）。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"66,67"
    }
    ]
    },
    {
    "id":null,
    "node":"乙方客户经理信息",
    "subList":[
    {
    "id":12800,
    "labelType":"content",
    "name":"姓名",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":" 林艺",
    "content":" 林艺",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"合同履行过程中具体事项的乙方经理人，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方客户经理名称缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    }
    ]
    },
    {
    "id":null,
    "node":"服务费用与支付",
    "subList":[
    {
    "id":12849,
    "labelType":"row",
    "name":"保证金条款",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"为规避乙方资金风险，避免甲方由于客观原因导致的不能及时支付采购款项、甲方同意向乙方缴纳履约保证金。第一阶段双方协商日交易金额为拾万，则第一阶段甲方需要交纳的保证金额度为20000；如甲方日交易金额变更，则保证金额度按照20000。奯乙方针对甲方交纳的保证金开具收据，甲方需妥善保存，协议终止保证金应优先清偿甲方对乙方的欠款（如有）；优先清偿完毕且甲乙双方没有任何应结算款项后，剩余保证金乙方须在3个工作日内一次性无息退还甲方。奯保证金自本合同签订之日起3个工作日内缴纳，逾期未交的，则合同自动失效；甲方可通过银行转账的方式向乙方缴纳保证金。",
    "content":"为规避乙方资金风险，避免甲方由于客观原因导致的不能及时支付采购款项、甲方同意向乙方缴纳履约保证金。第一阶段双方协商日交易金额为拾万，则第一阶段甲方需要交纳的保证金额度为20000；如甲方日交易金额变更，则保证金额度按照20000。奯乙方针对甲方交纳的保证金开具收据，甲方需妥善保存，协议终止保证金应优先清偿甲方对乙方的欠款（如有）；优先清偿完毕且甲乙双方没有任何应结算款项后，剩余保证金乙方须在3个工作日内一次性无息退还甲方。奯保证金自本合同签订之日起3个工作日内缴纳，逾期未交的，则合同自动失效；甲方可通过银行转账的方式向乙方缴纳保证金。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"本条款约定合同项下保证金相关事项，涉及到履约保证金的支付、结算、责任等，必须具体明确约定，且符合法律法规；",
    "ruleSuggestion":"履约保证金的支付期限、结算时限等期限可以根据交易习惯调整，但应明确具体，不可模糊例如出现“合理”、“适当期限”等模糊性描述；我方时限越长越有利，对方的约束时限越短越有利；",
    "ruleWarn":"保证金约定条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"为规避乙方资金风险，避免甲方由于客观原因导致的不能及时支付采购款项、甲方同意向乙方缴纳履约保证金。第一阶段双方协商日交易金额为，则第一阶段甲方需要交纳的保证金额度为；如甲方日交易金额变更，则保证金额度按照。乙方针对甲方交纳的保证金开具收据，甲方需妥善保存，协议终止保证金应优先清偿甲方对乙方的欠款（如有）；优先清偿完毕且甲乙双方没有任何应结算款项后，剩余保证金乙方须在3个工作日内一次性无息退还甲方。保证金自本合同签订之日起3个工作日内缴纳，逾期未交的，则合同自动失效；甲方可通过银行转账的方式向乙方缴纳保证金。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"48,49,50"
    }
    ]
    },
    {
    "id":null,
    "node":"合同内容条款",
    "subList":[
    {
    "id":12844,
    "labelType":"row",
    "name":"服务内容",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"服务内容奯乙方开放网络、电话、QQ、微信、电子邮件等渠道，向甲方提供订购机票服务。",
    "content":"服务内容奯乙方开放网络、电话、QQ、微信、电子邮件等渠道，向甲方提供订购机票服务。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"本条款是对合同内容的概括与描述，应当与合同项下保持一致，需谨慎修改；",
    "ruleSuggestion":"可以根据具体项目实际情况进行修改，需同步商务、业务；",
    "ruleWarn":"合同内容条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"服务内容乙方开放网络、电话、QQ、微信、电子邮件等渠道，向甲方提供订购机票服务。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"24,25"
    },
    {
    "id":12845,
    "labelType":"row",
    "name":"甲方权利与义务",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"权利和义务奯甲方权利和义务奯甲方应按照乙方要求提供公司营业执照副本的复印件及其他签署本协议所必须的文件。甲方应保证该类文件真实、有效；甲方违反此项规定造成乙方损失的，甲方应当承担直接经济损失。奯甲方在协议期内应向乙方提供完整真实的负责人联系方式、出行人员相关信息等。",
    "content":"权利和义务奯甲方权利和义务奯甲方应按照乙方要求提供公司营业执照副本的复印件及其他签署本协议所必须的文件。甲方应保证该类文件真实、有效；甲方违反此项规定造成乙方损失的，甲方应当承担直接经济损失。奯甲方在协议期内应向乙方提供完整真实的负责人联系方式、出行人员相关信息等。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"本条款约定甲方的在合同项下享有的权利和应当承担的义务，影响合同的履行、合同目的的实现、甲方权益的保证，需谨慎修改；",
    "ruleSuggestion":"可以根据具体项目实际情况进行修改，需同步商务、业务；",
    "ruleWarn":"甲方权利与义务条款有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"权利和义务甲方权利和义务甲方应按照乙方要求提供公司营业执照副本的复印件及其他签署本协议所必须的文件。甲方应保证该类文件真实、有效；甲方违反此项规定造成乙方损失的，甲方应当承担直接经济损失。甲方在协议期内应向乙方提供完整真实的负责人联系方式、出行人员相关信息等。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"26,27,28,29"
    },
    {
    "id":12847,
    "labelType":"row",
    "name":"合同损失承担范围",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"协议双方都不承担任何由于违反本协议规定或者未接受协议规定提供的服务而给对方造成的非直接损失或间接利益损失。",
    "content":"协议双方都不承担任何由于违反本协议规定或者未接受协议规定提供的服务而给对方造成的非直接损失或间接利益损失。",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":"协议双方都不承担任何由于违反本协议规定或者未接受协议规定提供的服务而给对方造成的非直接损失或间接利益损失。",
    "ruleRisk":"此处约定，本合同项下的损失承担范围，不包括间接利益损失，仅包含直接损失；",
    "ruleSuggestion":"建议恢复原模板标准条款；",
    "ruleWarn":"合同损失承担范围有修改",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"协议双方都不承担任何由于违反本协议规定或者未接受协议规定提供的服务而给对方造成的非直接损失或间接利益损失。"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"46"
    },
    {
    "id":12839,
    "labelType":"row",
    "name":"合同名称",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"机票采购合作服务协议",
    "content":"机票合作服务协议",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"合同名称体现合同性质、合同目的；",
    "ruleSuggestion":"本合同名称体现的合同性质已确定，即“采购”，须在合同名称中体现“采购”字样；",
    "ruleWarn":"合同性质有误",
    "rules":[
    {
    "compareType":"compare",
    "key":"include",
    "oper":";",
    "source":null,
    "value":"采购"
    }
    ],
    "type":"bool"
    }
    },
    {
    "mentionList":[
    {
    "compareContent":"机票采购合作服务协议",
    "content":"机票合作服务协议",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"合同名称体现合同性质、合同目的；",
    "ruleSuggestion":"本合同名称体现的合同性质已确定，即“采购”；如将“协议”修改为“合同”，合同名称体现的文书性质即是合同或协议，可以接受；如将“协议”删除，并且合同名称中无体现文书性质的词，不能接受，合同名称应当体现文书性质；",
    "ruleWarn":"合同名称不规范",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":null,
    "value":"机票采购合作服务协议"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":"1,2"
    }
    ]
    },
    {
    "id":null,
    "node":"变更与审核时限",
    "subList":[
    {
    "id":12811,
    "labelType":"content",
    "name":"变更请求审核时限",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"110",
    "content":"110",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"依据本合同性质和合同目的，乙方顶票服务应当满足甲方的需要，我方提出请求变更申请后，设定乙方的审核时限为60分钟以内，时间不宜过长，否则影响甲方商务活动和业务的顺利进行；",
    "ruleSuggestion":"请修改；",
    "ruleWarn":"变更请求乙方审核时限过长",
    "rules":[
    {
    "compareType":null,
    "key":null,
    "oper":"",
    "source":null,
    "value":"${181-变更与审核时限-变更请求审核时限}<=60"
    }
    ],
    "type":"calculate"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12807,
    "labelType":"content",
    "name":"乙方出票时限（分钟）",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"40",
    "content":"40",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":"数值小于等于30；",
    "ruleRisk":"依据本合同性质和合同目的，乙方出票义务应当满足甲方的需要，我方设定出票时限为订单支付成功后30分钟内，时间不宜过长，否则影响甲方商务活动和业务的顺利进行；",
    "ruleSuggestion":"请修改出票时限，建议修改为30分钟以下；",
    "ruleWarn":"乙方出票时间过长",
    "rules":[
    {
    "compareType":null,
    "key":null,
    "oper":"",
    "source":null,
    "value":"${181-变更与审核时限-乙方出票时限（分钟）}<=30"
    }
    ],
    "type":"calculate"
    }
    }
    ],
    "rowNums":""
    }
    ]
    },
    {
    "id":null,
    "node":"支付对账与账号信息",
    "subList":[
    {
    "id":12827,
    "labelType":"content",
    "name":"收款账户名称",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"",
    "content":"",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"交易方银行账户、开票账户等基本信息涉及到合同费用支付、合同履行，应当完整必备；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"账户名称缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12818,
    "labelType":"content",
    "name":"第一阶段保证金",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"20000",
    "content":"20000",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":"数值小于等于10000；",
    "ruleRisk":"此处的保证金是指为规避乙方资金风险，避免甲方不能及时支付款项，甲方同意向乙方缴纳履约保证金，依据我司相关规定和合同标的金额，保证金金额不易过高；",
    "ruleSuggestion":"请修改，建议保证金在10000元以下；",
    "ruleWarn":"保证金金额过高",
    "rules":[
    {
    "compareType":null,
    "key":null,
    "oper":"",
    "source":null,
    "value":"${181-支付对账与账号信息-第一阶段保证金}<=10000"
    }
    ],
    "type":"calculate"
    }
    }
    ],
    "rowNums":""
    }
    ]
    },
    {
    "id":null,
    "node":"交易方基本信息",
    "subList":[
    {
    "id":12777,
    "labelType":"content",
    "name":"甲方-联系人",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"林一 ",
    "content":"林一 ",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"合同当事方联系人信息是合同各方沟通、通知的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方联系人缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12786,
    "labelType":"content",
    "name":"乙方-联系邮箱",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"1348990@163.com",
    "content":"1348990@163.com",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方联系邮箱缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12774,
    "labelType":"content",
    "name":"甲方名称",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"深圳高高网络科技有限责任公司",
    "content":"深圳高高网络科技有限责任公司",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"wdnmd",
    "ruleSuggestion":"wdnmd",
    "ruleWarn":"wdnmd",
    "rules":[
    {
    "compareType":"compare",
    "key":"equal",
    "oper":";",
    "source":"深圳高高网络科技有限责任公司",
    "value":"#[companyInfo^交易方基本信息-甲方名称]"
    }
    ],
    "type":"bool"
    }
    },
    {
    "mentionList":[
    {
    "compareContent":"深圳高高网络科技有限责任公司",
    "content":"深圳高高网络科技有限责任公司",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，名称是其中的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方名称缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12781,
    "labelType":"content",
    "name":"乙方名称",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"大宴航空公司",
    "content":"大宴航空公司",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，名称是其中的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方名称缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12783,
    "labelType":"content",
    "name":"乙方注册地址",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"",
    "content":"",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，注册地址信息是其中的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方注册地址缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    },
    {
    "mentionList":[
    {
    "compareContent":"",
    "content":"",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，注册地址信息是其中的关键信息，应当真实准确并精确到“区”级；",
    "ruleSuggestion":"请据实填写、并精确到“区”级；",
    "ruleWarn":"乙方注册地址模糊",
    "rules":[
    {
    "compareType":"compare",
    "key":"include",
    "oper":";",
    "source":null,
    "value":"区"
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12787,
    "labelType":"content",
    "name":"乙方-联系地址",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"广东省广州市",
    "content":"广东省广州市",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方联系地址缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12785,
    "labelType":"content",
    "name":"乙方-联系电话",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"13299908779 ",
    "content":"13299908779 ",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方联系电话缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    },
    {
    "mentionList":[
    {
    "compareContent":"13299908779 ",
    "content":"13299908779 ",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，应当准确无误、符合电话号码构成逻辑；",
    "ruleSuggestion":"请重新核对、确保信息真实准确；",
    "ruleWarn":"乙方联系电话有误",
    "rules":[
    {
    "compareType":"check",
    "key":"digitPhone",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12782,
    "labelType":"content",
    "name":"乙方法定代表人",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"何云",
    "content":"何云",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，法定代表人信息是其中的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方法定代表人缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12778,
    "labelType":"content",
    "name":"甲方-联系电话",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"13668902 ",
    "content":"13668902 ",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方联系电话缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    },
    {
    "mentionList":[
    {
    "compareContent":"13668902 ",
    "content":"13668902 ",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，联系电话应当真实、准确、符合电话号码逻辑；",
    "ruleSuggestion":"请重新核对、确保准确无误；",
    "ruleWarn":"甲方联系电话有误",
    "rules":[
    {
    "compareType":"check",
    "key":"digitPhone",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12779,
    "labelType":"content",
    "name":"甲方-联系邮箱",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"56linlin@sd.com",
    "content":"56linlin@sd.com",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方联系邮箱缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12784,
    "labelType":"content",
    "name":"乙方-联系人",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"秦凌 ",
    "content":"秦凌 ",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"合同当事方联系人信息是合同各方沟通、通知的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"乙方联系人缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12776,
    "labelType":"content",
    "name":"甲方注册地址",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"广东省深圳市大马街32号",
    "content":"广东省深圳市大马街32号",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，注册地址信息是其中的关键信息，地址信息应当精确到“区”级；",
    "ruleSuggestion":"请据实补充完整，确保精确无误；",
    "ruleWarn":"甲方注册地址模糊",
    "rules":[
    {
    "compareType":"compare",
    "key":"include",
    "oper":";",
    "source":null,
    "value":"区"
    }
    ],
    "type":"bool"
    }
    },
    {
    "mentionList":[
    {
    "compareContent":"广东省深圳市大马街32号",
    "content":"广东省深圳市大马街32号",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，注册地址信息是其中的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方注册地址缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12775,
    "labelType":"content",
    "name":"甲方法定代表人",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"王小高",
    "content":"王小高",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":2,
    "ruleLevelName":"中",
    "ruleReference":null,
    "ruleRisk":"交易方基本信息是判断交易方是否真实可靠的依据，法定代表人信息是其中的关键信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方法定代表人缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    },
    {
    "id":12780,
    "labelType":"content",
    "name":"甲方-联系地址",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"广东省深圳市大马街32号-2",
    "content":"广东省深圳市大马街32号-2",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":3,
    "ruleLevelName":"低",
    "ruleReference":null,
    "ruleRisk":"合同当事人的各项联系方式是联系人之间沟通、通知的重要方式信息，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方联系地址缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    }
    ]
    },
    {
    "id":null,
    "node":"甲方授权负责人信息",
    "subList":[
    {
    "id":12793,
    "labelType":"content",
    "name":"姓名",
    "order":0,
    "riskItemList":[
    {
    "mentionList":[
    {
    "compareContent":"王晓",
    "content":"王晓",
    "endIndex":0,
    "endLineNumber":0,
    "lineNumber":0,
    "score":0.0,
    "startIndex":0
    }
    ],
    "risk":{
    "ruleLevel":1,
    "ruleLevelName":"高",
    "ruleReference":null,
    "ruleRisk":"合同履行过程中具体事项的甲方授权负责人，不能缺失；",
    "ruleSuggestion":"请据实补充完整；",
    "ruleWarn":"甲方授权负责人名称缺失",
    "rules":[
    {
    "compareType":"check",
    "key":"exist",
    "oper":";",
    "source":null,
    "value":null
    }
    ],
    "type":"bool"
    }
    }
    ],
    "rowNums":""
    }
    ]
    }
    ]
    
  ngOnInit(): void {
    this.taskService.addTask(true,'showSub')
    this.router.getRouteParams().subscribe(item=>{
      get("http://"+this.host+"/web-apps/apps/api/documents/api.js", () => {
        //Google Maps library has been loaded...
        console.log('load api.js 成功')
        // let url = 'http://mall.jenkin.tech:9002/jenkin/%E9%94%80%E5%94%AE01%EF%BC%88%E6%8C%89%E4%BB%BD%EF%BC%89-%E5%8B%BF%E5%8A%A8.docx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=jenkin%2F20210102%2F%2Fs3%2Faws4_request&X-Amz-Date=20210102T132143Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=5cce89a0b8f6369659c8f7cee0f13ffa5362604eebe192b371fd3d8ede78bf80';
        // let name = '销售01（按份-勿动.docx';
        //npm install --save js-base64
        let token  = Base64.encode(localStorage.getItem('token'));
        // let url = "http://mall.jenkin.tech:10013/lsc/system/downloadFile?code="+item.code+"&token="+token
        let fileUrl = "http://"+this.backhost+":8050/lsc/files/file/downloadFile?code="+item.code+"&token="+token
        // let url = "http://192.168.3.48:8050/lsc/system/downloadFile?code="+item.code
        console.log("文件下载地址:"+fileUrl)
        let name =   item.name;
        if(ObjectUtils.isNotEmpty(name)&&ObjectUtils.isNotEmpty(item.code)){
          let fileCode =  Base64.encode(item.code) 
          this.saveurl = "http://"+this.backhost+":8050/lsc/files/file/docx/save?token="+token+"&fileId="+item.id
          this.initEditor(name,fileUrl, fileCode ,"edit","desktop",token,item.id)
        }
    });
    })
    


  }
   

  
   initEditor(name,url,docKey, mode, type,token,id) {
   
    //creating object editing
    let pageH = document.documentElement.clientHeight
    let h = pageH-(pageH*0.2);
    let docType = name.substring(name.lastIndexOf(".") + 1).trim().toLowerCase();
    this.api = new DocsAPI.DocEditor("placeholder",

      {

        type: type,

        width: (type == "desktop" ? "100%" : undefined),

        height: (type == "desktop" ? h : undefined),

        documentType: this.getDocumentType(docType),

        document: {

          title: name,

          url: url,

          fileType: docType,

          key: docKey,
          // var config = DE.getController('Main').document;
          myRisk: this.data,
          riskHeight: (h*0.8)+'px',
          permissions: {

            edit: true

          }

        },
        
        editorConfig: {
          region: "zh-CN",
          lang: "zh",
          location: "zh",
          mode: mode,
          callbackUrl: "http://"+this.backhost+":8050/lsc/files/file/docx/save?token="+token+"&fileId="+id,
        },
        "services": {
          "CoAuthoring": {
              "token": {
                  "inbox": {
                      "inBody": true,
                  },
                  "outbox": {
                      "inBody": true
                  }
              }
          }
      },
        token: token,

      });
     
      console.log('测试api',this.api )
      
      window.addEventListener('message',function(event){
               
        console.log("收到" 
            + event.origin + "的消息：" + event.data )
      })

   }
   test(){
    this.api.serviceCommand('search:next','合同')
   }
   getDocumentType(ext) {

    if (".doc.docx.docm.dot.dotx.dotm.odt.fodt.ott.rtf.txt.html.htm.mht.pdf.djvu.fb2.epub.xps".indexOf(ext) != -1) return "text";

    if (".xls.xlsx.xlsm.xlt.xltx.xltm.ods.fods.ots.csv".indexOf(ext) != -1) return "spreadsheet";

    if (".pps.ppsx.ppsm.ppt.pptx.pptm.pot.potx.potm.odp.fodp.otp".indexOf(ext) != -1) return "presentation";

    return null;

};




}
